name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
        
      - name: Run markdownlint
        run: markdownlint '*.md' --ignore node_modules
        
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress '*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  check-file-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check file size
        run: |
          find . -name "*.md" -type f -exec du -h {} \; | sort -hr
          find . -name "*.md" -type f -size +3M | while read file; do
            echo "::warning::File $file is larger than 3MB"
          done 